USE [master]
GO
/****** Object:  Database [GymMembership]    Script Date: 3/22/2021 9:43:29 PM ******/
CREATE DATABASE [GymMembership]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GymMembership', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GymMembership.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GymMembership_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GymMembership_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GymMembership] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GymMembership].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GymMembership] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GymMembership] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GymMembership] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GymMembership] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GymMembership] SET ARITHABORT OFF 
GO
ALTER DATABASE [GymMembership] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GymMembership] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GymMembership] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GymMembership] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GymMembership] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GymMembership] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GymMembership] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GymMembership] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GymMembership] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GymMembership] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GymMembership] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GymMembership] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GymMembership] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GymMembership] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GymMembership] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GymMembership] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GymMembership] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GymMembership] SET RECOVERY FULL 
GO
ALTER DATABASE [GymMembership] SET  MULTI_USER 
GO
ALTER DATABASE [GymMembership] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GymMembership] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GymMembership] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GymMembership] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GymMembership] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GymMembership] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GymMembership', N'ON'
GO
ALTER DATABASE [GymMembership] SET QUERY_STORE = OFF
GO
USE [GymMembership]
GO
/****** Object:  Table [dbo].[Memberships]    Script Date: 3/22/2021 9:43:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Memberships](
	[membership_id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NULL,
	[membership_expiration] [datetime] NULL,
	[balance_due] [decimal](16, 2) NULL,
 CONSTRAINT [PK_Memberships] PRIMARY KEY CLUSTERED 
(
	[membership_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 3/22/2021 9:43:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[user_id] [int] IDENTITY(1,1) NOT NULL,
	[user_first_name] [varchar](50) NULL,
	[user_last_name] [varchar](50) NULL,
	[user_join_date] [datetime] NULL,
	[user_birthday] [datetime] NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[users] ON 
GO
INSERT [dbo].[users] ([user_id], [user_first_name], [user_last_name], [user_join_date], [user_birthday]) VALUES (1, N'Test', N'Test', CAST(N'2020-04-04T00:00:00.000' AS DateTime), CAST(N'2001-04-01T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[users] ([user_id], [user_first_name], [user_last_name], [user_join_date], [user_birthday]) VALUES (2, N'Johnny', N'Test', CAST(N'2021-03-22T21:41:28.677' AS DateTime), CAST(N'2012-06-05T21:41:28.000' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[users] OFF
GO
ALTER TABLE [dbo].[Memberships]  WITH CHECK ADD  CONSTRAINT [FK_Memberships_Memberships] FOREIGN KEY([membership_id])
REFERENCES [dbo].[Memberships] ([membership_id])
GO
ALTER TABLE [dbo].[Memberships] CHECK CONSTRAINT [FK_Memberships_Memberships]
GO
USE [master]
GO
ALTER DATABASE [GymMembership] SET  READ_WRITE 
GO
